apiVersion: v1
kind: Pod
metadata:
  name: red
  labels:
    name: ashour
spec:
  containers:
  - name: myapp-redis
    image: redis

  initContainers:
  - name: mybusybox
    image: busybox
    args: ["sleep","20"]