---
apiVersion: v1
kind: Pod
metadata:
  name: myjavaapp
spec:
  containers:
  - name: app
    image: ashor11/java_data_struct_app:v600
    command: ["/bin/sh"]
    stdin: true
    tty: true
    resources:
      requests:
        memory: "64Mi"
        cpu: "250m"
      limits:
        memory: "128Mi"
        cpu: "500m"