---
apiVersion: v1
kind: Pod
metadata:
  name: myjavaapp
spec:
  containers:
  - name: app
    image: ashor11/java_data_struct_app:v600
    command: ["/bin/sh"]
    stdin: true
    tty: true
