apiVersion: v1
kind: Service
metadata:
    name: service-1
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: proxy
  ports:
    - port: 80
      targetPort: http-web
      nodePort: 30008
